"""Reproducible ML scoring trained exclusively on documented synthetic data."""

from functools import lru_cache

from sklearn.ensemble import GradientBoostingClassifier

FEATURE_COLUMNS = (
    "registration_confirmed",
    "documentation_confirmed",
    "deprecated",
    "removed_from_supported_surface",
    "zombie_lifecycle",
    "runtime_only_evidence",
    "source_count",
    "endpoint_age_days",
    "known_threat_finding_count",
    "simulation_finding_count",
)

TRAINING_DATA_DESCRIPTION = (
    "GradientBoostingClassifier trained on reproducible synthetic inventory scenarios only; "
    "it does not represent production security incidents or real-world accuracy."
)


def _synthetic_training_data() -> tuple[list[list[float]], list[int]]:
    """Create labelled demonstration scenarios from controlled feature combinations.

    Labels encode illustrative low (0) through critical (3) exposure tiers. They
    are generated by the same transparent assumptions used for demonstration,
    not from real APIs, incidents, or vulnerability data.
    """
    rows: list[list[float]] = []
    labels: list[int] = []
    for registered in (0, 1):
        for documented in (0, 1):
            for deprecated in (0, 1):
                for removed in (0, 1):
                    for zombie in (0, 1):
                        for runtime_only in (0, 1):
                            for age_days in (7, 120, 730):
                                for threat_count in (0, 1, 2):
                                    for simulation_count in (0, 1, 2):
                                        source_count = 1 if runtime_only else 2
                                        exposure = (
                                    (1.0 if not registered else 0.0)
                                    + (1.0 if not documented else 0.0)
                                    + (1.25 if deprecated else 0.0)
                                    + (1.5 if removed else 0.0)
                                    + (2.5 if zombie else 0.0)
                                    + (1.25 if runtime_only else 0.0)
                                    + (0.25 if source_count == 1 else 0.0)
                                        + (0.25 if age_days >= 365 else 0.0)
                                            + min(2.0, threat_count * 1.0)
                                            + min(1.5, simulation_count * 0.75)
                                        )
                                        label = 0 if exposure < 1 else 1 if exposure < 2.5 else 2 if exposure < 4 else 3
                                        rows.append([registered, documented, deprecated, removed, zombie, runtime_only, source_count, age_days, threat_count, simulation_count])
                                        labels.append(label)
    return rows, labels


@lru_cache(maxsize=1)
def get_risk_model() -> GradientBoostingClassifier:
    rows, labels = _synthetic_training_data()
    model = GradientBoostingClassifier(random_state=42, n_estimators=60, max_depth=2)
    model.fit(rows, labels)
    return model


class SyntheticMLRiskScorer:
    """Return a 0-100 expected risk tier from the synthetic demonstration model."""

    def score(self, features: dict[str, int | float | str | dict[str, str]]) -> float:
        row = [[float(features[column]) for column in FEATURE_COLUMNS]]
        probabilities = get_risk_model().predict_proba(row)[0]
        expected_tier = sum(float(tier) * float(probability) for tier, probability in zip(get_risk_model().classes_, probabilities))
        return round((expected_tier / 3) * 100, 2)
